### ISSUE TITLE
parsetree non-functional on windows?

### ISSUE THREAD

**Issue by knausj85** [pokey/cursorless-vscode#1]
i haven't had a chance to dig into this yet, but parse tree appears to be non-functional on windows at the moment

from the extension log:
```
[2021-05-10 16:23:45.226] [exthost] [error] Activating extension pokey.parse-tree failed due to an error:
[2021-05-10 16:23:45.227] [exthost] [error] Error: \\?\c:\Users\knaus\.vscode\extensions\pokey.parse-tree-0.2.0\node_modules\tree-sitter\build\Release\tree_sitter_runtime_binding.node is not a valid Win32 application.
\\?\c:\Users\knaus\.vscode\extensions\pokey.parse-tree-0.2.0\node_modules\tree-sitter\build\Release\tree_sitter_runtime_binding.node
	at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
	at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
	at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at Object.<anonymous> (c:\Users\knaus\.vscode\extensions\pokey.parse-tree-0.2.0\node_modules\tree-sitter\index.js:3:13)
	at Module.u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at Object.<anonymous> (c:\Users\knaus\.vscode\extensions\pokey.parse-tree-0.2.0\out\extension.js:14:16)
	at Module.u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at require (internal/modules/cjs/helpers.js:72:18)
	at Function.t [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
	at h._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:25918)
	at h._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12016)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11072)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-05-10 16:23:45.453] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-05-10 16:23:45.453] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/github/dist/extension.js
[2021-05-10 16:23:45.459] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-05-10 16:23:45.459] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-05-10 16:23:45.535] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"extensionId":{"value":"ms-python.vscode-pylance","_lower":"ms-python.vscode-pylance"},"activationEvent":"onLanguage:python"}
[2021-05-10 16:23:45.535] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/knaus/.vscode/extensions/ms-python.python-2021.4.765268190/out/client/extension
[2021-05-10 16:23:45.648] [exthost] [info] eager extensions activated
[2021-05-10 16:23:45.677] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-05-10 16:23:45.677] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/github-authentication/dist/extension.js
[2021-05-10 16:23:45.686] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-05-10 16:23:45.686] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-05-10 16:23:45.693] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-05-10 16:23:45.693] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-05-10 16:23:45.697] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl-recommender","_lower":"ms-vscode-remote.remote-wsl-recommender"},"activationEvent":"onStartupFinished"}
[2021-05-10 16:23:45.697] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode-remote.remote-wsl-recommender/dist/extension.js
[2021-05-10 16:23:45.704] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-05-10 16:23:45.704] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/testing-editor-contributions/dist/extension.js
[2021-05-10 16:23:45.707] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":false,"extensionId":{"value":"dbaeumer.vscode-eslint","_lower":"dbaeumer.vscode-eslint"},"activationEvent":"onStartupFinished"}
[2021-05-10 16:23:45.707] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/knaus/.vscode/extensions/dbaeumer.vscode-eslint-2.1.20/client/out/extension
[2021-05-10 16:23:45.714] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onStartupFinished"}
[2021-05-10 16:23:45.714] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/knaus/.vscode/extensions/ms-vscode-remote.remote-wsl-0.54.6/dist/extension
[2021-05-10 16:23:45.979] [exthost] [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance {"startup":false,"extensionId":{"value":"ms-python.vscode-pylance","_lower":"ms-python.vscode-pylance"},"activationEvent":"onLanguage:python"}
[2021-05-10 16:23:45.979] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/knaus/.vscode/extensions/ms-python.vscode-pylance-2021.4.3/dist/extension.bundle.js
[2021-05-10 16:24:27.651] [exthost] [info] extension host terminating: received terminate message from renderer
[2021-05-10 16:24:28.671] [exthost] [info] exiting with code 0
[2021-05-10 16:24:28.907] [exthost] [info] extension host started
[2021-05-10 16:24:28.976] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-05-10 16:24:28.976] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-05-10 16:24:28.984] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-05-10 16:24:28.984] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-05-10 16:24:28.986] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-05-10 16:24:28.986] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Program Files/Microsoft VS Code/resources/app/extensions/git/dist/main
[2021-05-10 16:24:28.999] [exthost] [info] ExtensionService#_doActivateExtension pokey.command-server {"startup":true,"extensionId":{"value":"pokey.command-server","_lower":"pokey.command-server"},"activationEvent":"*"}
[2021-05-10 16:24:28.999] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/knaus/.vscode/extensions/pokey.command-server-0.3.4/out/extension.js
[2021-05-10 16:24:29.002] [exthost] [info] ExtensionService#_doActivateExtension pokey.parse-tree {"startup":true,"extensionId":{"value":"pokey.cursorless","_lower":"pokey.cursorless"},"activationEvent":"*"}
[2021-05-10 16:24:29.002] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/knaus/.vscode/extensions/pokey.parse-tree-0.2.0/out/extension.js
[2021-05-10 16:24:29.008] [exthost] [error] Activating extension pokey.parse-tree failed due to an error:
[2021-05-10 16:24:29.009] [exthost] [error] Error: \\?\c:\Users\knaus\.vscode\extensions\pokey.parse-tree-0.2.0\node_modules\tree-sitter\build\Release\tree_sitter_runtime_binding.node is not a valid Win32 application.
\\?\c:\Users\knaus\.vscode\extensions\pokey.parse-tree-0.2.0\node_modules\tree-sitter\build\Release\tree_sitter_runtime_binding.node
	at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
	at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
	at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at Object.<anonymous> (c:\Users\knaus\.vscode\extensions\pokey.parse-tree-0.2.0\node_modules\tree-sitter\index.js:3:13)
	at Module.u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:694)
	at Object.<anonymous> (c:\Users\knaus\.vscode\extensions\pokey.parse-tree-0.2.0\out\extension.js:14:16)
	at Module.u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1248)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:27791)
	at Function.E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:24509)
	at Function.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:59194)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at require (internal/modules/cjs/helpers.js:72:18)
	at Function.t [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
	at h._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:25918)
	at h._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12016)
	at h._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11072)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Promise.all (index 3)
	at async Promise.all (index 0)
```

**Comment by pokey** [comment]
Should be fixed in the latest version of [vscode-parse-tree](https://marketplace.visualstudio.com/items?itemName=pokey.parse-tree).  Mind giving that a whirl?

**Comment by pokey** [comment]
(for posterity's sake, fixed in https://github.com/pokey/vscode-parse-tree/commit/ca009d013b91eeced68321c43472b31628a576d7)
