### ISSUE TITLE
Indicating last subword by number causes error

### ISSUE THREAD

**Issue by brxck** [pokey/cursorless-vscode#9]
For example "take third word" in the word `fooBarBaz` yields:

```
Cannot read property 'end' of undefined
```

Of course one could say "take last word" instead, which does work.

Full trace from the extension host:

```
[2021-06-22 11:54:18.382] [exthost] [error] TypeError: Cannot read property 'end' of undefined
	at xv (/home/brock/.vscode/extensions/pokey.cursorless-0.14.0/dist/extension.js:23:9154)
	at /home/brock/.vscode/extensions/pokey.cursorless-0.14.0/dist/extension.js:23:7738
	at Array.map (<anonymous>)
	at as (/home/brock/.vscode/extensions/pokey.cursorless-0.14.0/dist/extension.js:23:7731)
	at $c (/home/brock/.vscode/extensions/pokey.cursorless-0.14.0/dist/extension.js:23:6721)
	at /home/brock/.vscode/extensions/pokey.cursorless-0.14.0/dist/extension.js:23:6551
	at Array.map (<anonymous>)
	at ss (/home/brock/.vscode/extensions/pokey.cursorless-0.14.0/dist/extension.js:23:6544)
	at /home/brock/.vscode/extensions/pokey.cursorless-0.14.0/dist/extension.js:23:12407
	at E._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:107932)
	at E._doExecuteCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:107077)
	at E.executeCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:106983)
	at Object.executeCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:21346)
	at CommandRunner.<anonymous> (/home/brock/.vscode/extensions/pokey.command-server-0.5.1/out/commandRunner.js:76:56)
	at Generator.next (<anonymous>)
	at fulfilled (/home/brock/.vscode/extensions/pokey.command-server-0.5.1/out/commandRunner.js:5:58) cursorless.command
```

**Comment by pokey** [comment]
Thanks for filing this one; should be an easy fix
